# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://deepCLEM.github.io
title: deepCLEM Home
email: rmenchon@dlpi.tel.uva.es
author: deepCLEM
description: > # "Write an awesome description for your new site here. 
  Deep Learning-aided label-free Correlative Light Electron Microscopy.
copyright: 'Copyright &copy; 2024 deepCLEM. All Rights Reserved.'
credits: '<a href="https://lpi.tel.uva.es/">Laboratorio de Procesado de Imagen (LPI)</a>. ETSI de Telecomunicación. Universidad de Valladolid. 
          Paseo Belén, 15 47011 Valladolid, Spain.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  #- title: twitter
   # url: 
  - title: github
    url: https://github.com/deepCLEM
  - title: send
    mailto: rmenchon@dlpi.tel.uva.es  
